// ==============================================================
// flap_printer_params.scad — AUTO-GENERATED FILE
// Generated by: pvv_tools.flap_printer
// Active jig: standard (5 insert row(s))
//
// DO NOT EDIT MANUALLY.
// Edit the 'jig' section in the job JSON file instead,
// then run: python -m pvv_tools.flap_printer <job.json>
//
// Coordinates are in printer orientation (matching the physical jig
// on the eufyMake E1 flatbed viewed from above): the mat's long
// axis runs along X; the zero-point / corner-cut corner is at the
// bottom-right.  Flap pockets sit rotated 90° (spool edge facing
// right), in rows along X (insert_rows of them on multi-row beds).
// ==============================================================

// ---- Flap physical dimensions (read from PVV_splitflap_mods.scad by Python) ----
flap_width = 54.0;
flap_height = 43.0;
flap_pin_width = 1.4;
flap_corner_radius = 3.1;
flap_notch_height = 15.0;
flap_notch_depth = 3.2;

// ---- eufyMake minibed mat outer geometry ----
flatbed_mat_size_x = 370.0;
flatbed_mat_size_y = 440.0;
flatbed_mat_corner_radius = 7.5;
flatbed_mat_corner_cut = 22.0;

// ---- Printable area (mat absolute coordinates) ----
flatbed_printable_size_x = 333.0;
flatbed_printable_size_y = 418.0;
flatbed_printable_origin_x = 4.0;
flatbed_printable_origin_y = 11.0;

// ---- Registration mark geometry ----
flatbed_reg_mark_size = 6.0;
flatbed_reg_mark_stroke = 1.0;
flatbed_reg_mark_extent_x = 333.0;  // same as printable_size_x

// ---- Jig grid parameters ----
flatbed_flap_jig_num_flaps_x = 6;
flatbed_flap_jig_num_flaps_y = 1;
flatbed_flap_jig_laser_kerf = 0.04;    // inward offset to tighten flap pocket fit
flatbed_flap_jig_insert_kerf = 0.04;   // outward offset on insert outline
flatbed_flap_jig_gap_x = 6.0;
flatbed_flap_jig_gap_y = 6.0;
flatbed_flap_jig_margin_x = 6.0;
flatbed_flap_jig_margin_y = 6.0;

// ---- Derived jig dimensions (computed by Python from the parameters above) ----
// Pockets are rotated 90°: X extent = flap_height, Y extent = flap_width.
flatbed_flap_jig_space_x = 49;    // flap_height(43.0) + gap_x(6.0)
flatbed_flap_jig_space_y = 60;    // flap_width(54.0) + gap_y(6.0)
flatbed_flap_jig_insert_size_x = 300;   // space_x*num_x - gap_x + 2*margin_x
flatbed_flap_jig_insert_size_y = 66;   // space_y*num_y - gap_y + 2*margin_y

// ---- Insert position (mat absolute coordinates) ----
flatbed_insert_origin_x = 20.5;
flatbed_insert_origin_y = 25.0;

// ---- Insert rows (standard flatbed stacks identical inserts along Y) ----
flatbed_insert_rows = 5;
flatbed_insert_pitch_y = 81.0;
