// ==============================================================
// flap_printer_params.scad — AUTO-GENERATED FILE
// Generated by: pvv_tools.flap_printer
//
// DO NOT EDIT MANUALLY.
// Edit the 'jig' section in the job JSON file instead,
// then run: python -m pvv_tools.flap_printer <job.json>
// ==============================================================

// ---- Flap physical dimensions (read from PVV_splitflap_mods.scad by Python) ----
flap_width = 54.0;
flap_height = 43.0;
flap_pin_width = 1.4;
flap_corner_radius = 3.1;
flap_notch_height = 15.0;
flap_notch_depth = 3.2;

// ---- eufyMake minibed mat outer geometry ----
minibed_mat_size_x = 97.0;
minibed_mat_size_y = 370.0;
minibed_mat_corner_radius = 7.5;
minibed_mat_corner_cut = 22.0;

// ---- Printable area (mat absolute coordinates) ----
minibed_printable_size_x = 88.0;
minibed_printable_size_y = 333.0;
minibed_printable_origin_x = 5.0;
minibed_printable_origin_y = 33.0;

// ---- Registration mark geometry ----
minibed_reg_mark_size = 6.0;
minibed_reg_mark_stroke = 1.0;
minibed_reg_mark_extent_y = 333.0;  // same as printable_size_y

// ---- Jig grid parameters ----
minibed_flap_jig_num_flaps_x = 1;
minibed_flap_jig_num_flaps_y = 6;
minibed_flap_jig_laser_kerf = 0.04;    // inward offset to tighten flap pocket fit
minibed_flap_jig_insert_kerf = 0.04;   // outward offset on insert outline
minibed_flap_jig_gap_x = 6.0;
minibed_flap_jig_gap_y = 6.0;
minibed_flap_jig_margin_x = 6.0;
minibed_flap_jig_margin_y = 6.0;

// ---- Derived jig dimensions (computed by Python from the parameters above) ----
minibed_flap_jig_space_x = 60;    // flap_width(54.0) + gap_x(6.0)
minibed_flap_jig_space_y = 49;    // flap_height(43.0) + gap_y(6.0)
minibed_flap_jig_insert_size_x = 66;   // space_x*num_x - gap_x + 2*margin_x
minibed_flap_jig_insert_size_y = 300;   // space_y*num_y - gap_y + 2*margin_y

// ---- Insert position (mat absolute coordinates) ----
minibed_insert_origin_x = 16.0;
minibed_insert_origin_y = 49.5;
