/*
   Flap Printer Laser Cut Jig — eufyMake minibed
   Copyright 2026 Phil Van Valkenberg

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.

   This file generates laser-cut SVG files for the flap UV-printing jig.

   Parameters are driven by:
       pvv_cad/flap_printer_params.scad    (auto-generated by pvv_tools.flap_printer)

   To regenerate the params file, run:
       python -m pvv_tools.flap_printer <job.json>

   A committed default params file (matching prototype_job.json) is provided so
   this file can be opened in OpenSCAD without running Python first.
*/

// ---- Geometry dependencies ----
use<../3d/flap.scad>;       // flap_2d() — 2D flap pocket profile
use<../3d/shapes.scad>;     // rounded_square()
include<../3d/global_constants.scad>;  // eps

// ---- Jig, mat, and flap dimension parameters (auto-generated by pvv_tools.flap_printer) ----
include<flap_printer_params.scad>;


// ==========================================================================================
// Mat profile modules
// ==========================================================================================

module eufy_minibed_printable_area_profile()
{
	translate([minibed_printable_origin_x, minibed_printable_origin_y])
		square([minibed_printable_size_x, minibed_printable_size_y], center=false);
}

module eufy_corner_cut_profile()
{
	polygon([
		[0, 0],
		[minibed_mat_corner_cut, 0],
		[0, minibed_mat_corner_cut]
	]);
}

module eufy_minibed_mat_profile(bUseCornerCut = true, bUsePrintableAreaCut = true)
{
	difference()
	{
		rounded_square([minibed_mat_size_x, minibed_mat_size_y], center=false, r=minibed_mat_corner_radius, $fn = 30);

		if (bUseCornerCut)
			eufy_corner_cut_profile();

		if (bUsePrintableAreaCut)
			eufy_minibed_printable_area_profile();
	}
}

//eufy_minibed_mat_profile();


// ==========================================================================================
// Jig modules
// ==========================================================================================

module eufy_minibed_flap_jig_insert_profile()
{
	translate([minibed_insert_origin_x, minibed_insert_origin_y])
		square([minibed_flap_jig_insert_size_x, minibed_flap_jig_insert_size_y], center=false);
}

module eufy_minibed_flap_jig_flaps()
{
	for (flap_number = [0 : minibed_flap_jig_num_flaps_y - 1])
	{
		translate([minibed_insert_origin_x + minibed_flap_jig_margin_x,
		           minibed_insert_origin_y + minibed_flap_jig_margin_y + flap_number * minibed_flap_jig_space_y, 0])
		{
			offset(delta=-minibed_flap_jig_laser_kerf) flap_2d();
		}
	}
}
//eufy_minibed_flap_jig_flaps();

module eufy_minibed_registration_marks()
{
	// L-shaped marks at the four corners of the registration box,
	// positioned OUTSIDE the rectangle.
	s = minibed_reg_mark_size;
	t = minibed_reg_mark_stroke;
	x0 = minibed_printable_origin_x;
	y0 = minibed_printable_origin_y;
	x1 = minibed_printable_origin_x + minibed_printable_size_x;
	y1 = minibed_printable_origin_y + minibed_reg_mark_extent_y;

	// Bottom-left corner: arms run right along bottom edge, up along left edge
	translate([x0 + t, y0 - t]) square([s - t, t]);
	translate([x0 - t, y0 + t]) square([t, s - t]);

	// Bottom-right corner: arms run left along bottom edge, up along right edge
	translate([x1 - s, y0 - t]) square([s - t, t]);
	translate([x1, y0 + t]) square([t, s - t]);

	// Top-left corner: arms run right along top edge, down along left edge
	translate([x0 + t, y1]) square([s - t, t]);
	translate([x0 - t, y1 - s]) square([t, s - t]);

	// Top-right corner: arms run left along top edge, down along right edge
	translate([x1 - s, y1]) square([s - t, t]);
	translate([x1, y1 - s]) square([t, s - t]);
}

module eufy_minibed_flap_jig(bUseCornerCut = true, bGenInsertOnly = true, bUseRegistrationMarks = true)
{
	if (bGenInsertOnly)
	{
		difference()
		{
			offset(delta=minibed_flap_jig_insert_kerf) eufy_minibed_flap_jig_insert_profile();
			eufy_minibed_flap_jig_flaps();
		}
	}
	else
	{
		difference()
		{
			rounded_square([minibed_mat_size_x, minibed_mat_size_y], center=false, r=minibed_mat_corner_radius, $fn = 30);

			if (bUseCornerCut)
				eufy_corner_cut_profile();

			eufy_minibed_flap_jig_insert_profile();

			if (bUseRegistrationMarks)
				eufy_minibed_registration_marks();

			// Fingernail relief at insert origin corner for lifting the insert mat
			translate([minibed_insert_origin_x, minibed_insert_origin_y]) circle(r = 5, $fn = 60);
		}
	}
}

// ---- Default render: insert only ----
// To render the full outer jig instead, change bGenInsertOnly to false.
eufy_minibed_flap_jig(bGenInsertOnly = true);
