/*
   Flap Printer Laser Cut Jig — eufyMake minibed
   Copyright 2026 Phil Van Valkenberg

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.

   This file generates laser-cut SVG files for the flap UV-printing jig.

   ORIENTATION CONVENTION
   The jig is modeled exactly as it sits on the eufyMake E1 flatbed, viewed
   from above: the mat's long axis runs along X (370 mm left/right).  The
   mat zero-point corner — the one with the diagonal corner cut — is at the
   bottom-right, matching the eufyMake Studio Zero Point origin (lower-right
   of the imported print image).  Flap pockets sit rotated 90° (spool/notch
   edge facing right, toward the zero point), in rows along X.  The Python
   renderer's output images use this same frame, so the OpenSCAD top view,
   the print image, and the physical flatbed all look identical.

   FLATBEDS
   The same laser-cut INSERT serves both beds; only the outer jig differs:
     - Mini Flatbed:     mat 370 × 97,  1 insert row
     - Standard Flatbed: mat 370 × 440, 5 insert rows at insert_pitch_y
   The row count/pitch come from the params file (flatbed_insert_rows /
   flatbed_insert_pitch_y), i.e. from the ACTIVE jig of the last Python run.

   Parameters are driven by:
       pvv_cad/flap_printer_params.scad    (auto-generated by pvv_tools.flap_printer)

   To regenerate the params file, run:
       python -m pvv_tools.flap_printer <job.json>            (active jig)
       python -m pvv_tools.flap_printer <job.json> --jig standard

   A committed default params file (matching prototype_job.json's active jig)
   is provided so this file can be opened in OpenSCAD without running Python
   first.
*/

// ---- Geometry dependencies ----
use<../3d/flap.scad>;       // flap_2d() — 2D flap pocket profile
use<../3d/shapes.scad>;     // rounded_square()
include<../3d/global_constants.scad>;  // eps

// ---- Jig, mat, and flap dimension parameters (auto-generated by pvv_tools.flap_printer) ----
include<flap_printer_params.scad>;


// ==========================================================================================
// Mat profile modules
// ==========================================================================================

module eufy_flatbed_printable_area_profile()
{
	translate([flatbed_printable_origin_x, flatbed_printable_origin_y])
		square([flatbed_printable_size_x, flatbed_printable_size_y], center=false);
}

// Diagonal cut at the mat zero-point corner (bottom-right)
module eufy_corner_cut_profile()
{
	polygon([
		[flatbed_mat_size_x, 0],
		[flatbed_mat_size_x - flatbed_mat_corner_cut, 0],
		[flatbed_mat_size_x, flatbed_mat_corner_cut]
	]);
}

module eufy_flatbed_mat_profile(bUseCornerCut = true, bUsePrintableAreaCut = true)
{
	difference()
	{
		rounded_square([flatbed_mat_size_x, flatbed_mat_size_y], center=false, r=flatbed_mat_corner_radius, $fn = 30);

		if (bUseCornerCut)
			eufy_corner_cut_profile();

		if (bUsePrintableAreaCut)
			eufy_flatbed_printable_area_profile();
	}
}

//eufy_flatbed_mat_profile();


// ==========================================================================================
// Jig modules
// ==========================================================================================

// One insert outline.  row selects the insert row on multi-row beds
// (row 0 = the insert_origin row; rows repeat at flatbed_insert_pitch_y).
module eufy_flatbed_flap_jig_insert_profile(row = 0)
{
	translate([flatbed_insert_origin_x, flatbed_insert_origin_y + row * flatbed_insert_pitch_y])
		square([flatbed_flap_jig_insert_size_x, flatbed_flap_jig_insert_size_y], center=false);
}

// All insert outlines of the active bed (1 on the minibed, 5 on the standard)
module eufy_flatbed_flap_jig_insert_profiles()
{
	for (row = [0 : flatbed_insert_rows - 1])
		eufy_flatbed_flap_jig_insert_profile(row);
}

module eufy_flatbed_flap_jig_flaps(row = 0)
{
	// flap_2d() is drawn upright (flap_width along X, spool/notch edge at the
	// bottom).  In the jig each flap sits rotated 90° CCW, so its spool edge
	// faces right (toward the mat zero point) and its height (flap_height)
	// runs along the mat's long axis.
	for (flap_number = [0 : flatbed_flap_jig_num_flaps_x - 1])
	{
		translate([flatbed_insert_origin_x + flatbed_flap_jig_margin_x + flap_number * flatbed_flap_jig_space_x + flap_height,
		           flatbed_insert_origin_y + row * flatbed_insert_pitch_y + flatbed_flap_jig_margin_y, 0])
		{
			rotate(90) offset(delta=-flatbed_flap_jig_laser_kerf) flap_2d();
		}
	}
}
//eufy_flatbed_flap_jig_flaps();

module eufy_flatbed_registration_marks()
{
	// L-shaped marks at the four corners of the registration box,
	// positioned OUTSIDE the rectangle.
	s = flatbed_reg_mark_size;
	t = flatbed_reg_mark_stroke;
	x0 = flatbed_printable_origin_x;
	y0 = flatbed_printable_origin_y;
	x1 = flatbed_printable_origin_x + flatbed_reg_mark_extent_x;
	y1 = flatbed_printable_origin_y + flatbed_printable_size_y;

	// Bottom-left corner: arms run right along bottom edge, up along left edge
	translate([x0 + t, y0 - t]) square([s - t, t]);
	translate([x0 - t, y0 + t]) square([t, s - t]);

	// Bottom-right corner: arms run left along bottom edge, up along right edge
	translate([x1 - s, y0 - t]) square([s - t, t]);
	translate([x1, y0 + t]) square([t, s - t]);

	// Top-left corner: arms run right along top edge, down along left edge
	translate([x0 + t, y1]) square([s - t, t]);
	translate([x0 - t, y1 - s]) square([t, s - t]);

	// Top-right corner: arms run left along top edge, down along right edge
	translate([x1 - s, y1]) square([s - t, t]);
	translate([x1, y1 - s]) square([t, s - t]);
}

module eufy_flatbed_flap_jig(bUseCornerCut = true, bGenInsertOnly = true, bUseRegistrationMarks = true)
{
	if (bGenInsertOnly)
	{
		// A single insert — identical for both beds (cut 5 for the standard)
		difference()
		{
			offset(delta=flatbed_flap_jig_insert_kerf) eufy_flatbed_flap_jig_insert_profile();
			eufy_flatbed_flap_jig_flaps();
		}
	}
	else
	{
		difference()
		{
			rounded_square([flatbed_mat_size_x, flatbed_mat_size_y], center=false, r=flatbed_mat_corner_radius, $fn = 30);

			if (bUseCornerCut)
				eufy_corner_cut_profile();

			eufy_flatbed_flap_jig_insert_profiles();

			if (bUseRegistrationMarks)
				eufy_flatbed_registration_marks();

			// Fingernail relief for lifting each insert mat, at the insert
			// corner nearest the mat zero point (bottom-right)
			for (row = [0 : flatbed_insert_rows - 1])
				translate([flatbed_insert_origin_x + flatbed_flap_jig_insert_size_x,
				           flatbed_insert_origin_y + row * flatbed_insert_pitch_y]) circle(r = 5, $fn = 60);
		}
	}
}

// ---- Default render: insert only ----
// To render the full outer jig instead, change bGenInsertOnly to false.
eufy_flatbed_flap_jig(bGenInsertOnly = false);
