"""JSON job-file loader, validator, and config dataclasses."""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

# Root of pre-rendered per-character flap SVG assets.  Each font preset
# occupies its own subdirectory: assets/flap_glyphs/<PresetName>/.
# Generated by pvv_tools/generate_epilogue_flap_svgs.py; committed to the
# repo so flap_printer has no runtime OpenSCAD dependency for glyph types.
_GLYPH_ASSETS_DIR = Path(__file__).resolve().parent.parent / 'assets' / 'flap_glyphs'

# Downloaded Twemoji SVGs for the "emoji" flap type.
# Populated by pvv_tools/download_emoji.py; files may be hand-edited before
# committing.  Files are named by CLDR short name, e.g. heart.svg.
_EMOJI_ASSETS_DIR = Path(__file__).resolve().parent.parent / 'assets' / 'emoji'

# Must stay in sync with 3d/flap_characters.scad and CHARACTER_LIST
# in pvv_tools/generate_epilogue_flap_svgs.py.
_FLAP_CHARACTER_LIST = " ABCDEFGHIJKLMNOPQRSTUVWXYZg0123456789r.?-$'#yp,!@&w"

# ---------------------------------------------------------------------------
# Dataclasses
# ---------------------------------------------------------------------------

@dataclass
class DisplayConfig:
    num_modules: int = 48
    module_pitch_mm: float = 64.0
    inter_module_gap_mm: float = 10.0


@dataclass
class JigConfig:
    """Jig geometry in printer orientation.

    All coordinates match the physical jig on the eufyMake E1 Mini Flatbed
    viewed from above: the mat's long axis runs along X, and the mat
    zero-point (corner-cut) corner is at the bottom-right.  The OpenSCAD
    model, the output print images, and the physical flatbed all share this
    frame.  Flap pockets sit rotated 90° (spool edge facing right), so a
    pocket's X extent is flap_height and its Y extent is flap_width.
    """
    type: str = "minibed"
    flip_mode: str = "front-back"        # "left-right" | "front-back"
    # Grid parameters — pockets run in a row along X (the mat's long axis)
    num_flaps_x: int = 6
    num_flaps_y: int = 1
    gap_x_mm: float = 6.0
    gap_y_mm: float = 6.0
    margin_x_mm: float = 6.0
    margin_y_mm: float = 6.0
    # Printable area — absolute coordinates on the mat
    printable_size_x_mm: float = 333.0
    printable_size_y_mm: float = 88.0
    printable_origin_x_mm: float = 4.0
    printable_origin_y_mm: float = 5.0
    # Insert lower-left corner — absolute coordinates on the mat.  With
    # multiple insert rows this is the FIRST insert; subsequent rows repeat
    # at insert_pitch_y_mm intervals along +Y.
    insert_origin_x_mm: float = 20.5
    insert_origin_y_mm: float = 16.0
    # Insert rows: the standard flatbed stacks several identical insert
    # jigs along Y (each flipped individually for the back pass).  The
    # minibed has a single row.
    insert_rows: int = 1
    insert_pitch_y_mm: Optional[float] = None   # required when insert_rows > 1
    # Per-jig overrides of output.calibration_offset_mm / output.canvas_size_mm
    # (zero-point error and Studio canvas are properties of the bed, not the job)
    calibration_offset_mm: Optional[tuple[float, float]] = None
    canvas_size_mm: Optional[tuple[float, float]] = None
    # Laser kerf compensations (mm)
    laser_kerf_mm: float = 0.04
    insert_kerf_mm: float = 0.04
    # Mat outer geometry (eufyMake hardware constants)
    mat_size_x_mm: float = 370.0
    mat_size_y_mm: float = 97.0
    mat_corner_radius_mm: float = 7.5
    mat_corner_cut_mm: float = 22.0
    # Registration mark geometry (for laser cut outer jig)
    reg_mark_size_mm: float = 6.0
    reg_mark_stroke_mm: float = 1.0


@dataclass
class OutputConfig:
    dpi: int = 360
    format: str = "png"
    bleed_mm: float = 1.0
    ink_save_mask: bool = True
    labels: bool = True
    label_font_size_pt: int = 6
    output_dir: str = "output"
    # Optional (width_mm, height_mm) override for the output image canvas.
    # When set, the canvas is treated as the eufyMake Studio mat working canvas
    # (origin = mat zero-point), and the jig insert is placed at absolute mat
    # coordinates from SCAD (flatbed_insert_origin_x/y).  Use this to match
    # eufyMake Studio's reported canvas size (e.g. [90, 335]) without
    # touching the physical jig dimensions.  Leave unset to use the SCAD
    # printable-area size.
    canvas_size_mm: Optional[tuple[float, float]] = None
    # If true, draw thin L-shaped registration marks at the four corners of
    # the output image (bottom-right is green = eufyMake origin, others white).
    # Useful for visually verifying jig-vs-print alignment.
    registration_marks: bool = False
    # Line width (mm) for registration marks.  Larger values are more visible
    # on the print and more reliable on lower-resolution print heads.
    registration_mark_line_width_mm: float = 1.0
    # Global (dx_mm, dy_mm) shift applied to every drawn element in the
    # final output image (flap art, ink-save mask, labels, and registration
    # marks all shift together).  Use this to compensate for a systematic
    # offset between the printer's zero-point and the physical jig (e.g.
    # the eufyMake Zero-Point calibration being off by a couple of mm).
    # Positive dx moves content toward +X (the long axis, away from the
    # zero point); positive dy moves content toward +Y (downward in the
    # image).  Content shifted past the image edge is clipped.
    calibration_offset_mm: tuple[float, float] = (0.0, 0.0)


@dataclass
class PreviewConfig:
    """Settings for the contact-sheet module preview image."""
    enabled: bool = False
    columns: int = 12
    cell_padding_mm: float = 3.0
    inter_cell_gap_mm: Optional[float] = None  # gap between cells; defaults to cell_padding_mm
    flap_color: tuple = (20, 20, 20)           # RGB — physical flap stock colour
    background_color: tuple = (245, 245, 245)  # RGB — overall canvas background
    label_color: tuple = (60, 60, 60)          # RGB — label text colour
    label_font_size_pt: int = 7
    dpi: int = 96
    filename: str = "preview.png"


VALID_FIT_MODES = ('fit', 'fill', 'stretch', 'contain')
VALID_NOTCH_MODES = ('none', 'inset', 'squeeze')


@dataclass
class GlobalTransforms:
    scale: tuple[float, float] = (1.0, 1.0)
    crop_percent: Optional[tuple[float, float, float, float]] = None  # (left%, top%, right%, bottom%)
    fit_mode: str = 'fit'                    # 'fit' | 'fill' | 'stretch' | 'contain'
    notch_mode: tuple[str, str] = ('none', 'none')  # (left, right)


@dataclass
class FlapSegment:
    """One module-range span of a multi-module flap.

    A multi-module flap is stitched from one or more segments, each covering
    an inclusive [start, end] module range with its own source image.
    Per-segment transform overrides fall back to the owning CustomFlap's
    values, then to the global defaults.  Segment ranges within one flap
    must not overlap; modules the job processes that no segment covers
    render as blanks (with a warning).
    """
    module_range: tuple[int, int]       # inclusive [start, end]
    source: Optional[str] = None        # image file path; None only when blank=True
    blank: bool = False                 # True → this range renders transparent (silences the gap warning)
    scale: Optional[tuple[float, float]] = None
    crop: Optional[tuple[float, float, float, float]] = None
    fit_mode: Optional[str] = None
    notch_mode: Optional[tuple[str, str]] = None
    offset_mm: Optional[tuple[float, float]] = None

    # Resolved at load time
    source_path: Optional[Path] = None


@dataclass
class CustomFlap:
    slot: int                           # 0-based index within the custom flap sequence; must be unique
    label: str                          # e.g. "EP42"
    source: Optional[str] = None        # image file path (resolved relative to config dir); None for blank
    type: str = "single"                # "single" | "multi-module" | "blank"
    module_range: Optional[tuple[int, int]] = None  # multi-module: overall [start, end] span across segments
    scale: Optional[tuple[float, float]] = None
    crop: Optional[tuple[float, float, float, float]] = None  # (left%, top%, right%, bottom%)
    fit_mode: Optional[str] = None    # per-image override; None = use global default
    notch_mode: Optional[tuple[str, str]] = None  # (left, right); None = use global default
    bleed: bool = True   # False → skip bleed edge-expansion for this image (ink-save mask still applied)
                         # Default: True for 'single'/'multi-module'; False for 'glyph'/'epilogue'/'emoji'/'blank'
    offset_mm: Optional[tuple[float, float]] = None  # [dx_mm, dy_mm] shift applied after fit, before slicing
    enabled: bool = True  # False → output is 100% transparent; slot position preserved

    # Multi-module only: the module-range segments this flap is stitched from.
    # A flat entry (source + module_range directly on the entry) is normalised
    # to a single segment at load time.
    segments: Optional[list[FlapSegment]] = None

    # Resolved at load time
    source_path: Optional[Path] = None

    def segment_for_module(self, module_index: int) -> Optional[FlapSegment]:
        """Return the segment covering *module_index*, or None."""
        if self.segments:
            for seg in self.segments:
                if seg.module_range[0] <= module_index <= seg.module_range[1]:
                    return seg
        return None


@dataclass
class DimensionOverrides:
    """Optional dimension fallbacks loaded from the job config.

    These values are used when OpenSCAD is not available to extract
    dimensions from the .scad source files.  Any field left as None
    will fall through to the hardcoded defaults in dimensions.py.
    """
    flap_width: Optional[float] = None
    flap_height: Optional[float] = None
    flap_gap: Optional[float] = None
    flap_corner_radius: Optional[float] = None
    flap_notch_height: Optional[float] = None
    flap_notch_depth: Optional[float] = None
    flap_pin_width: Optional[float] = None
    jig_num_x: Optional[int] = None
    jig_num_y: Optional[int] = None
    jig_gap_x: Optional[float] = None
    jig_gap_y: Optional[float] = None
    jig_margin_x: Optional[float] = None
    jig_margin_y: Optional[float] = None
    printable_width: Optional[float] = None
    printable_height: Optional[float] = None

    # Map from config-friendly names to SCAD echo tag names
    _KEY_MAP = {
        'flap_width': 'flap_width',
        'flap_height': 'flap_height',
        'flap_gap': 'flap_gap',
        'flap_corner_radius': 'flap_corner_radius',
        'flap_notch_height': 'flap_notch_height_default',
        'flap_notch_depth': 'flap_notch_depth',
        'flap_pin_width': 'flap_pin_width',
        'jig_num_x': 'flatbed_flap_jig_num_flaps_x',
        'jig_num_y': 'flatbed_flap_jig_num_flaps_y',
        'jig_gap_x': 'flatbed_flap_jig_gap_x',
        'jig_gap_y': 'flatbed_flap_jig_gap_y',
        'jig_margin_x': 'flatbed_flap_jig_margin_x',
        'jig_margin_y': 'flatbed_flap_jig_margin_y',
        'printable_width': 'flatbed_printable_size_x',
        'printable_height': 'flatbed_printable_size_y',
    }

    def as_dict(self) -> dict[str, float]:
        """Return non-None values keyed by SCAD echo tag names."""
        result = {}
        for config_key, scad_key in self._KEY_MAP.items():
            val = getattr(self, config_key)
            if val is not None:
                result[scad_key] = val
        return result


@dataclass
class JobConfig:
    display: DisplayConfig = field(default_factory=DisplayConfig)
    jig: JigConfig = field(default_factory=JigConfig)   # the ACTIVE jig
    output: OutputConfig = field(default_factory=OutputConfig)
    preview: PreviewConfig = field(default_factory=PreviewConfig)
    global_transforms: GlobalTransforms = field(default_factory=GlobalTransforms)
    custom_flaps: list[CustomFlap] = field(default_factory=list)
    dimensions: DimensionOverrides = field(default_factory=DimensionOverrides)

    # All jig definitions from the job file ("jigs" map, or the single "jig"
    # section under the name "default"), plus the active selection.
    jigs: dict[str, JigConfig] = field(default_factory=dict)
    active_jig: str = "default"

    # Metadata
    config_dir: Path = field(default_factory=lambda: Path('.'))

    def select_jig(self, name: str) -> None:
        """Switch the active jig (e.g. from the --jig CLI flag)."""
        if name not in self.jigs:
            raise ValueError(
                f"Unknown jig {name!r} (job file defines: {', '.join(sorted(self.jigs))})")
        self.active_jig = name
        self.jig = self.jigs[name]

# ---------------------------------------------------------------------------
# Loader
# ---------------------------------------------------------------------------

def _get(d: dict, key: str, default=None):
    """Get a value from a dict, returning default if missing or None."""
    val = d.get(key)
    return val if val is not None else default


def _parse_offset(raw, field_name: str = 'offset') -> tuple[float, float]:
    """Parse a [dx, dy] offset list/tuple into a (float, float) tuple."""
    if raw is None:
        return (0.0, 0.0)
    if len(raw) != 2:
        raise ValueError(f"{field_name} must be [dx_mm, dy_mm]")
    return (float(raw[0]), float(raw[1]))


def _parse_rgb(raw, field_name: str) -> tuple[int, int, int]:
    """Parse an [R, G, B] list into a (int, int, int) tuple."""
    if raw is None:
        raise ValueError(f"{field_name} must be [R, G, B]")
    if len(raw) != 3:
        raise ValueError(f"{field_name} must be [R, G, B], got: {raw!r}")
    return tuple(int(c) for c in raw)


def _parse_notch_mode(raw, field_name: str) -> tuple[str, str]:
    """Parse a notch_mode value: string (symmetric) or [left, right] list.

    A plain string like "inset" is expanded to ("inset", "inset").
    A two-element list like ["inset", "none"] becomes ("inset", "none").
    """
    if isinstance(raw, str):
        if raw not in VALID_NOTCH_MODES:
            raise ValueError(f"{field_name}: invalid notch_mode {raw!r} "
                             f"(expected one of {VALID_NOTCH_MODES})")
        return (raw, raw)
    if isinstance(raw, (list, tuple)) and len(raw) == 2:
        left, right = str(raw[0]), str(raw[1])
        for side, val in (('left', left), ('right', right)):
            if val not in VALID_NOTCH_MODES:
                raise ValueError(f"{field_name}: invalid notch_mode {side}={val!r} "
                                 f"(expected one of {VALID_NOTCH_MODES})")
        return (left, right)
    raise ValueError(
        f"{field_name}: notch_mode must be a string or [left, right] list, got: {raw!r}")


def _parse_segment(seg_raw: dict, config_dir: Path, ctx: str) -> FlapSegment:
    """Parse one multi-module segment dict (also used for the flat form)."""
    mr = seg_raw.get('module_range')
    if mr is None or len(mr) != 2:
        raise ValueError(f"{ctx}: 'module_range' is required and must be [start, end]")
    start, end = int(mr[0]), int(mr[1])
    if start > end:
        raise ValueError(f"{ctx}: module_range start ({start}) > end ({end})")

    blank = bool(seg_raw.get('blank', False))
    source = seg_raw.get('source')
    source_path: Optional[Path] = None
    if blank:
        if source is not None:
            logger.warning("%s: 'source' ignored for blank segment", ctx)
            source = None
    else:
        if source is None:
            raise ValueError(f"{ctx}: 'source' is required (or set \"blank\": true)")
        source_path = Path(source)
        if not source_path.is_absolute():
            source_path = config_dir / source_path

    fit_mode = seg_raw.get('fit_mode')
    if fit_mode is not None and fit_mode not in VALID_FIT_MODES:
        raise ValueError(f"{ctx}: invalid fit_mode {fit_mode!r} (expected one of {VALID_FIT_MODES})")

    scale = seg_raw.get('scale')
    crop = seg_raw.get('crop')
    return FlapSegment(
        module_range=(start, end),
        source=source,
        blank=blank,
        scale=tuple(scale) if scale else None,
        crop=tuple(crop) if crop else None,
        fit_mode=fit_mode,
        notch_mode=_parse_notch_mode(seg_raw['notch_mode'], f"{ctx}.notch_mode")
                   if seg_raw.get('notch_mode') is not None else None,
        offset_mm=_parse_offset(seg_raw['offset_mm'], f"{ctx}.offset_mm")
                  if seg_raw.get('offset_mm') is not None else None,
        source_path=source_path,
    )


def _load_preview(raw: dict) -> PreviewConfig:
    """Parse the optional 'preview' section from the job config dict."""
    pv = raw.get('preview', {})

    def _opt_color(key, default):
        val = pv.get(key)
        return _parse_rgb(val, f"preview.{key}") if val is not None else default

    raw_gap = pv.get('inter_cell_gap_mm')
    return PreviewConfig(
        enabled=bool(_get(pv, 'enabled', False)),
        columns=int(_get(pv, 'columns', 12)),
        cell_padding_mm=float(_get(pv, 'cell_padding_mm', 3.0)),
        inter_cell_gap_mm=float(raw_gap) if raw_gap is not None else None,
        flap_color=_opt_color('flap_color', (20, 20, 20)),
        background_color=_opt_color('background_color', (245, 245, 245)),
        label_color=_opt_color('label_color', (60, 60, 60)),
        label_font_size_pt=int(_get(pv, 'label_font_size_pt', 7)),
        dpi=int(_get(pv, 'dpi', 96)),
        filename=str(_get(pv, 'filename', 'preview.png')),
    )


def load_config(path: str | Path) -> JobConfig:
    """Load and validate a JSON job config file."""
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(f"Config file not found: {path}")

    with open(path, 'r', encoding='utf-8') as f:
        raw = json.load(f)

    config_dir = path.parent.resolve()

    # Display section
    d = raw.get('display', {})
    display = DisplayConfig(
        num_modules=_get(d, 'num_modules', 48),
        module_pitch_mm=_get(d, 'module_pitch_mm', 64.0),
        inter_module_gap_mm=_get(d, 'inter_module_gap_mm', 10.0),
    )

    # Jig section(s): either a single "jig" object, or a "jigs" map of named
    # definitions plus "active_jig" selecting one (overridable via --jig).
    def _load_jig(j: dict, ctx: str) -> JigConfig:
        if 'output_orientation' in j:
            logger.warning(
                "%s.output_orientation is obsolete and ignored — output images "
                "are always in printer orientation (long axis along X)", ctx)
        cal_raw = _get(j, 'calibration_offset_mm', None)
        canvas_raw = _get(j, 'canvas_size_mm', None)
        if canvas_raw is not None and len(canvas_raw) != 2:
            raise ValueError(f"{ctx}.canvas_size_mm must be [width_mm, height_mm]")
        pitch_raw = _get(j, 'insert_pitch_y_mm', None)
        jig = JigConfig(
            type=_get(j, 'type', 'minibed'),
            flip_mode=_get(j, 'flip_mode', 'front-back'),
            num_flaps_x=int(_get(j, 'num_flaps_x', 6)),
            num_flaps_y=int(_get(j, 'num_flaps_y', 1)),
            gap_x_mm=float(_get(j, 'gap_x_mm', 6.0)),
            gap_y_mm=float(_get(j, 'gap_y_mm', 6.0)),
            margin_x_mm=float(_get(j, 'margin_x_mm', 6.0)),
            margin_y_mm=float(_get(j, 'margin_y_mm', 6.0)),
            printable_size_x_mm=float(_get(j, 'printable_size_x_mm', 333.0)),
            printable_size_y_mm=float(_get(j, 'printable_size_y_mm', 88.0)),
            printable_origin_x_mm=float(_get(j, 'printable_origin_x_mm', 4.0)),
            printable_origin_y_mm=float(_get(j, 'printable_origin_y_mm', 5.0)),
            insert_origin_x_mm=float(_get(j, 'insert_origin_x_mm', 20.5)),
            insert_origin_y_mm=float(_get(j, 'insert_origin_y_mm', 16.0)),
            insert_rows=int(_get(j, 'insert_rows', 1)),
            insert_pitch_y_mm=float(pitch_raw) if pitch_raw is not None else None,
            calibration_offset_mm=_parse_offset(cal_raw, f'{ctx}.calibration_offset_mm')
                                  if cal_raw is not None else None,
            canvas_size_mm=(float(canvas_raw[0]), float(canvas_raw[1]))
                           if canvas_raw is not None else None,
            laser_kerf_mm=float(_get(j, 'laser_kerf_mm', 0.04)),
            insert_kerf_mm=float(_get(j, 'insert_kerf_mm', 0.04)),
            mat_size_x_mm=float(_get(j, 'mat_size_x_mm', 370.0)),
            mat_size_y_mm=float(_get(j, 'mat_size_y_mm', 97.0)),
            mat_corner_radius_mm=float(_get(j, 'mat_corner_radius_mm', 7.5)),
            mat_corner_cut_mm=float(_get(j, 'mat_corner_cut_mm', 22.0)),
            reg_mark_size_mm=float(_get(j, 'reg_mark_size_mm', 6.0)),
            reg_mark_stroke_mm=float(_get(j, 'reg_mark_stroke_mm', 1.0)),
        )
        if jig.flip_mode not in ('left-right', 'front-back'):
            raise ValueError(f"{ctx}: invalid flip_mode {jig.flip_mode!r} "
                             f"(expected 'left-right' or 'front-back')")
        if jig.insert_rows < 1:
            raise ValueError(f"{ctx}: insert_rows must be >= 1")
        if jig.insert_rows > 1:
            if jig.insert_pitch_y_mm is None:
                raise ValueError(f"{ctx}: insert_pitch_y_mm is required when insert_rows > 1")
            last_top = (jig.insert_origin_y_mm - jig.printable_origin_y_mm
                        + (jig.insert_rows - 1) * jig.insert_pitch_y_mm
                        + jig.margin_y_mm * 2 + 54.0)  # + insert height (flap width + margins)
            if last_top > jig.printable_size_y_mm + 1e-6:
                logger.warning(
                    "%s: %d insert rows at pitch %g mm extend past the printable "
                    "area (%g mm)", ctx, jig.insert_rows, jig.insert_pitch_y_mm,
                    jig.printable_size_y_mm)
        if jig.printable_size_x_mm < jig.printable_size_y_mm and jig.insert_rows == 1:
            logger.warning(
                "%s.printable_size_x_mm (%g) < printable_size_y_mm (%g) — this "
                "looks like a job file in the old rotated convention.  Jig "
                "coordinates are now in printer orientation: the long axis runs "
                "along X (e.g. printable area 333 x 88).  Swap the jig section's "
                "x/y values.",
                ctx, jig.printable_size_x_mm, jig.printable_size_y_mm)
        return jig

    if 'jigs' in raw:
        if 'jig' in raw:
            raise ValueError("Use either 'jig' or 'jigs' in the job file, not both")
        raw_jigs = raw['jigs']
        if not isinstance(raw_jigs, dict) or not raw_jigs:
            raise ValueError("'jigs' must be a non-empty object of named jig definitions")
        jigs = {name: _load_jig(jd, f"jigs.{name}") for name, jd in raw_jigs.items()}
        active = raw.get('active_jig')
        if active is None:
            if len(jigs) == 1:
                active = next(iter(jigs))
            else:
                raise ValueError(
                    f"'active_jig' is required when 'jigs' defines more than one jig "
                    f"(available: {', '.join(sorted(jigs))})")
        if active not in jigs:
            raise ValueError(
                f"active_jig {active!r} not found in 'jigs' (available: {', '.join(sorted(jigs))})")
    else:
        jigs = {'default': _load_jig(raw.get('jig', {}), 'jig')}
        active = 'default'
    jig = jigs[active]

    # Output section
    o = raw.get('output', {})
    canvas_raw = _get(o, 'canvas_size_mm', None)
    if canvas_raw is not None:
        if len(canvas_raw) != 2:
            raise ValueError("output.canvas_size_mm must be [width_mm, height_mm]")
        canvas_size = (float(canvas_raw[0]), float(canvas_raw[1]))
    else:
        canvas_size = None
    output = OutputConfig(
        dpi=_get(o, 'dpi', 360),
        format=_get(o, 'format', 'png'),
        bleed_mm=_get(o, 'bleed_mm', 1.0),
        ink_save_mask=_get(o, 'ink_save_mask', True),
        labels=_get(o, 'labels', True),
        label_font_size_pt=_get(o, 'label_font_size_pt', 6),
        output_dir=_get(o, 'output_dir', 'output'),
        canvas_size_mm=canvas_size,
        registration_marks=_get(o, 'registration_marks', False),
        registration_mark_line_width_mm=_get(o, 'registration_mark_line_width_mm', 1.0),
        calibration_offset_mm=_parse_offset(_get(o, 'calibration_offset_mm', [0.0, 0.0]),
                                            'output.calibration_offset_mm'),
    )

    # Global transforms
    gt = raw.get('global_transforms', {})
    scale_raw = _get(gt, 'scale', [1.0, 1.0])
    crop_raw = _get(gt, 'crop_percent', None)
    global_transforms = GlobalTransforms(
        scale=tuple(scale_raw) if scale_raw else (1.0, 1.0),
        crop_percent=tuple(crop_raw) if crop_raw else None,
        fit_mode=_get(gt, 'fit_mode', 'fit'),
        notch_mode=_parse_notch_mode(_get(gt, 'notch_mode', 'none'), 'global_transforms.notch_mode'),
    )
    if global_transforms.fit_mode not in VALID_FIT_MODES:
        raise ValueError(f"Invalid global fit_mode: {global_transforms.fit_mode!r} (expected one of {VALID_FIT_MODES})")

    # Custom flaps
    custom_flaps = []
    for i, cf in enumerate(raw.get('custom_flaps', [])):
        if 'slot' not in cf:
            raise ValueError(f"custom_flaps[{i}]: 'slot' is required")

        flap_type = cf.get('type', 'single')

        # "emoji" resolves to a hand-edited Twemoji SVG from assets/emoji/.
        # Download SVGs first with: python pvv_tools/download_emoji.py "<char>"
        if flap_type == 'emoji':
            emoji_name = cf.get('name')
            emoji_char = cf.get('char')
            if emoji_name is None and emoji_char is None:
                raise ValueError(
                    f"custom_flaps[{i}]: type 'emoji' requires 'name' or 'char'")
            if emoji_name is None:
                # Resolve char → CLDR name, same logic as download_emoji.py.
                try:
                    import emoji as emoji_lib
                    demojized = emoji_lib.demojize(emoji_char, language='en')
                    if demojized.startswith(':') and demojized.endswith(':') and demojized.count(':') == 2:
                        emoji_name = demojized.strip(':').replace('_', '-')
                except ImportError:
                    pass
                if emoji_name is None:
                    emoji_name = '-'.join(
                        f'{ord(c):x}' for c in emoji_char if ord(c) != 0xFE0F)
            svg_path = _EMOJI_ASSETS_DIR / f'{emoji_name}.svg'
            if not svg_path.is_file():
                hint = f'python pvv_tools/download_emoji.py "{emoji_char}"' \
                    if emoji_char else f'python pvv_tools/download_emoji.py "<emoji>" --name {emoji_name}'
                raise ValueError(
                    f"custom_flaps[{i}]: emoji SVG not found: {svg_path}\n"
                    f"  Download it with: {hint}")
            cf['source'] = str(svg_path)
            flap_type = 'single'
            if 'label' not in cf:
                cf['label'] = emoji_name[:14]

        # "epilogue" is a backward-compatible alias for "glyph" with
        # font="Epilogue".
        if flap_type == 'epilogue':
            cf.setdefault('font', 'Epilogue')
            flap_type = 'glyph'

        # "glyph" resolves a pre-rendered per-character SVG from
        # assets/flap_glyphs/<font>/.  The SVGs are committed to the repo
        # so no runtime OpenSCAD is needed.  Re-run
        # generate_epilogue_flap_svgs.py to regenerate them.
        if flap_type == 'glyph':
            glyph_font = cf.get('font', 'Epilogue')
            glyph_dir = _GLYPH_ASSETS_DIR / glyph_font
            if not glyph_dir.is_dir():
                raise ValueError(
                    f"custom_flaps[{i}]: no glyph assets found for font "
                    f"{glyph_font!r} at {glyph_dir}. "
                    f"Run: python pvv_tools/generate_epilogue_flap_svgs.py "
                    f"--font {glyph_font!r}")
            ep_index = cf.get('index')
            ep_char = cf.get('char')
            if (ep_index is None) == (ep_char is None):
                raise ValueError(
                    f"custom_flaps[{i}]: type 'glyph' requires exactly one "
                    f"of 'index' (0-{len(_FLAP_CHARACTER_LIST) - 1}) or 'char'")
            if ep_char is not None:
                if len(ep_char) != 1 or ep_char not in _FLAP_CHARACTER_LIST:
                    raise ValueError(
                        f"custom_flaps[{i}]: 'char' {ep_char!r} is not in the "
                        f"character set {_FLAP_CHARACTER_LIST!r}")
                ep_index = _FLAP_CHARACTER_LIST.index(ep_char)
            if not (0 <= ep_index < len(_FLAP_CHARACTER_LIST)):
                raise ValueError(
                    f"custom_flaps[{i}]: 'index' {ep_index} out of range "
                    f"[0, {len(_FLAP_CHARACTER_LIST) - 1}]")
            cf['source'] = str(glyph_dir / f'flap_{ep_index:02d}.svg')
            flap_type = 'single'
            if 'label' not in cf:
                ep_char_resolved = _FLAP_CHARACTER_LIST[ep_index]
                cf['label'] = f"{glyph_font[:3]}-{ep_char_resolved!r}" if ep_char_resolved.strip() else f"{glyph_font[:3]}-SP"

        # Multi-module entries carry their sources in segments; other types
        # use an entry-level source.
        segments: Optional[list[FlapSegment]] = None
        source_str: Optional[str] = cf.get('source')
        source_path: Optional[Path] = None
        module_range: Optional[tuple[int, int]] = None

        if flap_type == 'multi-module':
            if cf.get('segments') is not None:
                if source_str is not None or cf.get('module_range') is not None:
                    raise ValueError(
                        f"custom_flaps[{i}]: use either 'segments' or flat "
                        f"'source' + 'module_range', not both")
                raw_segs = cf['segments']
                if not isinstance(raw_segs, list) or not raw_segs:
                    raise ValueError(f"custom_flaps[{i}]: 'segments' must be a non-empty list")
                segments = [_parse_segment(s, config_dir, f"custom_flaps[{i}].segments[{k}]")
                            for k, s in enumerate(raw_segs)]
                source_str = None
            else:
                # Flat form: source + module_range on the entry → one segment
                if cf.get('module_range') is None:
                    raise ValueError(
                        f"custom_flaps[{i}]: 'module_range' (or 'segments') is "
                        f"required for multi-module type")
                segments = [_parse_segment(
                    {'module_range': cf['module_range'], 'source': source_str},
                    config_dir, f"custom_flaps[{i}]")]
            segments.sort(key=lambda s: s.module_range[0])
            for a, b in zip(segments, segments[1:]):
                if b.module_range[0] <= a.module_range[1]:
                    raise ValueError(
                        f"custom_flaps[{i}]: segment module_ranges overlap: "
                        f"{list(a.module_range)} and {list(b.module_range)}")
            module_range = (segments[0].module_range[0], segments[-1].module_range[1])
        else:
            if cf.get('segments') is not None:
                raise ValueError(f"custom_flaps[{i}]: 'segments' is only valid for multi-module type")
            if cf.get('module_range') is not None:
                raise ValueError(
                    f"custom_flaps[{i}]: 'module_range' is only valid for multi-module "
                    f"type (for a partial-range blank, use a multi-module entry with a "
                    f"blank segment)")
            # 'source' is required for non-blank types
            if flap_type == 'blank':
                if source_str is not None:
                    logger.warning("custom_flaps[%d]: 'source' ignored for blank type", i)
                    source_str = None
            else:
                if source_str is None:
                    raise ValueError(f"custom_flaps[{i}]: 'source' is required for type '{flap_type}'")
                source_path = Path(source_str)
                if not source_path.is_absolute():
                    source_path = config_dir / source_path

        scale = cf.get('scale')
        crop = cf.get('crop')

        flap = CustomFlap(
            slot=cf['slot'],
            label=cf.get('label', f"EP{cf['slot'] + 42:02d}"),
            source=source_str,
            type=flap_type,
            module_range=module_range,
            scale=tuple(scale) if scale else None,
            crop=tuple(crop) if crop else None,
            fit_mode=cf.get('fit_mode', None),
            notch_mode=_parse_notch_mode(cf['notch_mode'], f"custom_flaps[{i}].notch_mode") if cf.get('notch_mode') is not None else None,
            bleed=bool(cf.get('bleed', cf.get('type', 'single') in ('single', 'multi-module'))),
            offset_mm=_parse_offset(cf['offset_mm'], f'custom_flaps[{i}].offset_mm') if cf.get('offset_mm') is not None else None,
            enabled=bool(cf.get('enabled', True)),
            segments=segments,
            source_path=source_path,
        )

        if flap.fit_mode is not None and flap.fit_mode not in VALID_FIT_MODES:
            raise ValueError(f"custom_flaps[{i}]: invalid fit_mode {flap.fit_mode!r} (expected one of {VALID_FIT_MODES})")
        # notch_mode is already validated by _parse_notch_mode at load time

        custom_flaps.append(flap)

    # Slots must be unique: one entry per physical flap position.
    seen_slots: dict[int, int] = {}
    for idx, flap in enumerate(custom_flaps):
        if flap.slot in seen_slots:
            raise ValueError(
                f"custom_flaps[{idx}]: duplicate slot {flap.slot} (already used by "
                f"custom_flaps[{seen_slots[flap.slot]}]). Each slot must appear exactly "
                f"once; to stitch a multi-module flap from several images, use a "
                f"'segments' list on one entry.")
        seen_slots[flap.slot] = idx

    # Dimension overrides (optional fallbacks when OpenSCAD is unavailable)
    dim = raw.get('dimensions', {})
    dimensions = DimensionOverrides(
        flap_width=dim.get('flap_width'),
        flap_height=dim.get('flap_height'),
        flap_gap=dim.get('flap_gap'),
        flap_corner_radius=dim.get('flap_corner_radius'),
        flap_notch_height=dim.get('flap_notch_height'),
        flap_notch_depth=dim.get('flap_notch_depth'),
        flap_pin_width=dim.get('flap_pin_width'),
        jig_num_x=int(dim['jig_num_x']) if dim.get('jig_num_x') is not None else None,
        jig_num_y=int(dim['jig_num_y']) if dim.get('jig_num_y') is not None else None,
        jig_gap_x=dim.get('jig_gap_x'),
        jig_gap_y=dim.get('jig_gap_y'),
        jig_margin_x=dim.get('jig_margin_x'),
        jig_margin_y=dim.get('jig_margin_y'),
        printable_width=dim.get('printable_width'),
        printable_height=dim.get('printable_height'),
    )

    config = JobConfig(
        display=display,
        jig=jig,
        output=output,
        preview=_load_preview(raw),
        global_transforms=global_transforms,
        custom_flaps=custom_flaps,
        dimensions=dimensions,
        jigs=jigs,
        active_jig=active,
        config_dir=config_dir,
    )

    logger.info("Loaded config: %d custom flaps, %d modules, %d DPI",
                len(custom_flaps), display.num_modules, output.dpi)
    return config


def print_summary(config: JobConfig) -> None:
    """Print a human-readable summary of the job config."""
    print(f"  Display: {config.display.num_modules} modules, "
          f"pitch={config.display.module_pitch_mm}mm, "
          f"gap={config.display.inter_module_gap_mm}mm")
    jig_name = f" '{config.active_jig}'" if len(config.jigs) > 1 else ""
    rows_info = f", insert_rows={config.jig.insert_rows}" if config.jig.insert_rows > 1 else ""
    print(f"  Jig: {config.jig.type}{jig_name}, flip={config.jig.flip_mode}{rows_info}")
    print(f"  Output: {config.output.dpi} DPI, format={config.output.format}, "
          f"bleed={config.output.bleed_mm}mm, mask={config.output.ink_save_mask}, "
          f"labels={config.output.labels}")
    print(f"  Output dir: {config.output.output_dir}")
    print(f"  Fit mode: {config.global_transforms.fit_mode} (global default)")
    print(f"  Custom flaps: {len(config.custom_flaps)}")
    for cf in config.custom_flaps:
        fit_info = f", fit={cf.fit_mode}" if cf.fit_mode else ""
        disabled_info = " [DISABLED]" if not cf.enabled else ""
        if cf.type == "multi-module":
            mod_info = f", modules {cf.module_range[0]}-{cf.module_range[1]}"
            print(f"    [{cf.label}] slot={cf.slot}, type={cf.type}{mod_info}{fit_info}{disabled_info}:")
            for seg in cf.segments or []:
                if seg.blank:
                    exists = "blank"
                elif seg.source_path and seg.source_path.exists():
                    exists = "OK"
                else:
                    exists = "MISSING"
                seg_fit = f", fit={seg.fit_mode}" if seg.fit_mode else ""
                print(f"      modules {seg.module_range[0]}-{seg.module_range[1]}{seg_fit}: "
                      f"source={seg.source} ({exists})")
            continue
        if cf.type == "blank":
            exists = "blank"
        elif cf.source_path and cf.source_path.exists():
            exists = "OK"
        else:
            exists = "MISSING"
        print(f"    [{cf.label}] slot={cf.slot}, type={cf.type}{fit_info}{disabled_info}, "
              f"source={cf.source} ({exists})")
