"""Write pvv_cad/flap_printer_params.scad from computed dimensions + jig config.

This file is consumed by pvv_cad/flap_printer_jigs.scad to drive the laser-cut
jig generator.  It is re-generated on every Python render so the SCAD file
always reflects the current job config.
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .config import JigConfig
    from .dimensions import AllDimensions


def write_flap_printer_params(
    path: str | Path,
    dims: 'AllDimensions',
    jig_config: 'JigConfig',
) -> None:
    """Write (or overwrite) flap_printer_params.scad with current job parameters.

    Args:
        path: Destination path for flap_printer_params.scad.
        dims: Resolved dimensions (flap physical dims come from here).
        jig_config: Jig / mat parameters from the job JSON config.
    """
    path = Path(path)
    f = dims.flap
    j = jig_config
    p = dims.printable

    # Derived jig values (mirrors JigDimensions.insert_size() formula)
    space_x = f.width + j.gap_x_mm
    space_y = f.height + j.gap_y_mm
    insert_size_x = space_x * j.num_flaps_x - j.gap_x_mm + 2 * j.margin_x_mm
    insert_size_y = space_y * j.num_flaps_y - j.gap_y_mm + 2 * j.margin_y_mm

    content = (
        "// ==============================================================\n"
        "// flap_printer_params.scad — AUTO-GENERATED FILE\n"
        "// Generated by: pvv_tools.flap_printer\n"
        "//\n"
        "// DO NOT EDIT MANUALLY.\n"
        "// Edit the 'jig' section in the job JSON file instead,\n"
        "// then run: python -m pvv_tools.flap_printer <job.json>\n"
        "// ==============================================================\n"
        "\n"
        "// ---- Flap physical dimensions (read from PVV_splitflap_mods.scad by Python) ----\n"
        f"flap_width = {f.width};\n"
        f"flap_height = {f.height};\n"
        f"flap_pin_width = {f.pin_width};\n"
        f"flap_corner_radius = {f.corner_radius};\n"
        f"flap_notch_height = {f.notch_height};\n"
        f"flap_notch_depth = {f.notch_depth};\n"
        "\n"
        "// ---- eufyMake minibed mat outer geometry ----\n"
        f"minibed_mat_size_x = {j.mat_size_x_mm};\n"
        f"minibed_mat_size_y = {j.mat_size_y_mm};\n"
        f"minibed_mat_corner_radius = {j.mat_corner_radius_mm};\n"
        f"minibed_mat_corner_cut = {j.mat_corner_cut_mm};\n"
        "\n"
        "// ---- Printable area (mat absolute coordinates) ----\n"
        f"minibed_printable_size_x = {j.printable_size_x_mm};\n"
        f"minibed_printable_size_y = {j.printable_size_y_mm};\n"
        f"minibed_printable_origin_x = {j.printable_origin_x_mm};\n"
        f"minibed_printable_origin_y = {j.printable_origin_y_mm};\n"
        "\n"
        "// ---- Registration mark geometry ----\n"
        f"minibed_reg_mark_size = {j.reg_mark_size_mm};\n"
        f"minibed_reg_mark_stroke = {j.reg_mark_stroke_mm};\n"
        f"minibed_reg_mark_extent_y = {j.printable_size_y_mm};  // same as printable_size_y\n"
        "\n"
        "// ---- Jig grid parameters ----\n"
        f"minibed_flap_jig_num_flaps_x = {j.num_flaps_x};\n"
        f"minibed_flap_jig_num_flaps_y = {j.num_flaps_y};\n"
        f"minibed_flap_jig_laser_kerf = {j.laser_kerf_mm};    // inward offset to tighten flap pocket fit\n"
        f"minibed_flap_jig_insert_kerf = {j.insert_kerf_mm};   // outward offset on insert outline\n"
        f"minibed_flap_jig_gap_x = {j.gap_x_mm};\n"
        f"minibed_flap_jig_gap_y = {j.gap_y_mm};\n"
        f"minibed_flap_jig_margin_x = {j.margin_x_mm};\n"
        f"minibed_flap_jig_margin_y = {j.margin_y_mm};\n"
        "\n"
        "// ---- Derived jig dimensions (computed by Python from the parameters above) ----\n"
        f"minibed_flap_jig_space_x = {space_x:.6g};    // flap_width({f.width}) + gap_x({j.gap_x_mm})\n"
        f"minibed_flap_jig_space_y = {space_y:.6g};    // flap_height({f.height}) + gap_y({j.gap_y_mm})\n"
        f"minibed_flap_jig_insert_size_x = {insert_size_x:.6g};   // space_x*num_x - gap_x + 2*margin_x\n"
        f"minibed_flap_jig_insert_size_y = {insert_size_y:.6g};   // space_y*num_y - gap_y + 2*margin_y\n"
        "\n"
        "// ---- Insert position (mat absolute coordinates) ----\n"
        f"minibed_insert_origin_x = {p.insert_origin_x};\n"
        f"minibed_insert_origin_y = {p.insert_origin_y};\n"
    )

    path.write_text(content, encoding='utf-8')
